name: CI ReUse Dev
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string

jobs:
  NodeJS_Build:
    if: ${{ inputs.appType == 'nodejs' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - run: npm install
        name: Download dependencies

  Maven_Build:
    if: ${{ inputs.appType == 'maven' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - run: mvn package
        name: Download dependencies
