name: CI ReUse Dev
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      docker_build:
        required: true
        type: string

jobs:
  NodeJS_Build:
    if: ${{ inputs.appType == 'nodejs' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - run: npm install
        name: Download dependencies
      - name: Docker Build
        if: ${{ inputs.docker_build == 'true' }}
        run: docker build .
  Maven_Build:
    if: ${{ inputs.appType == 'maven' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - run: mvn package
        name: Download dependencies

  Angular_Build:
    if: ${{ inputs.appType == 'angular' }}
    runs-on: self-hosted
    steps:
      - run: echo ng build
