name: CI ReUse PR
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
jobs:
  Build:
    uses: prashumps/roboshop-github-actions/.github/workflows/build.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'

